version: '2.2'
services:
  app:
    image: 0x7eff/open-source-catalog-demo
    ports:
      - "80:3000"
    links:
      - mongo
    restart: always
    env_file:
      - meteor.env
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    command: mongod --storageEngine=wiredTiger
    volumes:
      - mongodb:/data/db
    ports:
      - "27017:27017"
  python:
    image: python:3
    command: bash /opt/github_health/startup.sh
    stdin_open: true
    tty: true
    env_file:
      - python.env
    links:
      - mongo
    volumes:
      - ./github_health:/opt/github_health
volumes:
  mongodb: